#!/bin/sh

export THEME=$HOME/.config/bash/themes/agnoster-bash/agnoster.bash
if [[ -f $THEME ]]; then
    export DEFAULT_USER=`whoami`
    source $THEME
fi

prompt_context(){
	if [[ "$USER" == "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
		prompt_segment green black "$USER"
	fi
}

prompt_virtualenv(){
	if [[ -n "$VIRTUAL_ENV" ]]; then
		prompt_segment red black "$(basename $VIRTUAL_ENV)"
	elif [[ -n "$CONDA_DEFAULT_ENV" ]]; then
		prompt_segment red black "$CONDA_DEFAULT_ENV"
	fi
}
